# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Steps 1 Checkout with main branch
      uses: actions/checkout@v2
    - name: Steps 2 Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Steps 3 Build with Maven
      run: mvn clean install
    - name: Step 4 list the current directory
      run : ls -a
    - name: Step 5 What is in the target folder
      run: |
         cd target
         ls -a
    - name: Step 6 Set up maven cache 
      uses: actions/cache@v2
      with: 
         path: ~./m2
         key: ${{runner.os}}-m2-${{hashfiles('**pom.xml')}}
         restore-keys: ${{runner.os}}.m2
    - name: Step 7 copy directory to another folder
      run: mkdir staging && cp target staging
    
    - name: Step 7 check the war file is copied
      run: ls
   
         
    - name:  Step 8 Persist workflow data as artifact
      uses: actions/upload-artifact@v2
      with: 
         name: github-actions-artifact
         path: staging
          
      
        
